#############################################################################
# Makefile for building: libqjalaliconverter.so
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  qjalaliconverter.pro
# Template: app
# Command: C:\Qt\5.12.3\android_armv7\bin\qmake.exe -o Makefile qjalaliconverter.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = E:\Android\SNDK\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang
CXX           = E:\Android\SNDK\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain E:\Android\SNDK\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING --sysroot=E:\Android\SNDK\android-ndk-r20/sysroot -isystem E:\Android\SNDK\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi -isystem E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++/include -isystem E:\Android\SNDK\android-ndk-r20/sources/android/support/include -isystem E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain E:\Android\SNDK\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING --sysroot=E:\Android\SNDK\android-ndk-r20/sysroot -isystem E:\Android\SNDK\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi -isystem E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++/include -isystem E:\Android\SNDK\android-ndk-r20/sources/android/support/include -isystem E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IC:\Qt\5.12.3\android_armv7\include -IC:\Qt\5.12.3\android_armv7\include\QtWidgets -IC:\Qt\5.12.3\android_armv7\include\QtGui -IC:\Qt\5.12.3\android_armv7\include\QtCore -I. -I. -IC:\Qt\5.12.3\android_armv7\mkspecs\android-clang
QMAKE         = C:\Qt\5.12.3\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.12.3\android_armv7\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.12.3\android_armv7\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = libqjalaliconverter.so1.0.0
DISTDIR = D:\my_Projects\Programming\Qt\qjalaliconverter\.tmp\libqjalaliconverter.so1.0.0
LINK          = E:\Android\SNDK\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain E:\Android\SNDK\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -Wl,--exclude-libs,libunwind.a
LFLAGS        = --sysroot=E:\Android\SNDK\android-ndk-r20/platforms/android-16/arch-arm/ -Wl,-soname,libqjalaliconverter.so -Wl,-rpath=C:/Qt/5.12.3/android_armv7/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:/Qt/5.12.3/android_armv7/lib -lQt5Widgets -Lc:\Utils\Android\android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -lQt5Gui -lQt5Core -lGLESv2  -LE:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.so.16 -llog -lz -lm -ldl -lc
AR            = E:\Android\SNDK\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = E:\Android\SNDK\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		..\JalaliDate\qdatejalali.cpp moc_mainwindow.cpp \
		moc_qdatejalali.cpp
OBJECTS       = main.obj \
		mainwindow.obj \
		qdatejalali.obj \
		moc_mainwindow.obj \
		moc_qdatejalali.obj
DIST          =  mainwindow.h \
		..\JalaliDate\qdatejalali.h main.cpp \
		mainwindow.cpp \
		..\JalaliDate\qdatejalali.cpp
QMAKE_TARGET  = libqjalaliconverter.so
DESTDIR       = 
TARGET        = libqjalaliconverter.so


first: all
####### Build rules

libqjalaliconverter.so: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qjalaliconverter.pro C:\Qt\5.12.3\android_armv7\mkspecs\android-clang\qmake.conf C:\Qt\5.12.3\android_armv7\mkspecs\features\spec_pre.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\unix.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\linux.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\sanitize.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\gcc-base.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\gcc-base-unix.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\clang.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\qdevice.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\device_config.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\android-base-head.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\qconfig.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\qt_functions.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\qt_config.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\common\android-base-tail.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\android-clang\qmake.conf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\toolchain.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\default_pre.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\resolve_config.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\default_post.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\qml_debug.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\android\android.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\warn_on.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\qt.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\resources.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\moc.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\unix\opengl.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\uic.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\unix\thread.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\qmake_use.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\file_copies.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\exceptions.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\yacc.prf \
		C:\Qt\5.12.3\android_armv7\mkspecs\features\lex.prf \
		qjalaliconverter.pro \
		C:\Qt\5.12.3\android_armv7\lib\libQt5Widgets.prl \
		C:\Qt\5.12.3\android_armv7\lib\libQt5Gui.prl \
		C:\Qt\5.12.3\android_armv7\lib\libQt5Core.prl
	$(QMAKE) -o Makefile qjalaliconverter.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
C:\Qt\5.12.3\android_armv7\mkspecs\features\spec_pre.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\unix.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\linux.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\sanitize.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\gcc-base.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\gcc-base-unix.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\clang.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\qdevice.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\features\device_config.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\android-base-head.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\qconfig.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.12.3\android_armv7\mkspecs\features\qt_functions.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\qt_config.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\common\android-base-tail.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\android-clang\qmake.conf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\5.12.3\android_armv7\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\toolchain.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\default_pre.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\resolve_config.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\default_post.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\qml_debug.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\android\android.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\warn_on.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\qt.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\resources.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\moc.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\unix\opengl.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\uic.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\unix\thread.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\qmake_use.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\file_copies.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\testcase_targets.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\exceptions.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\yacc.prf:
C:\Qt\5.12.3\android_armv7\mkspecs\features\lex.prf:
qjalaliconverter.pro:
C:\Qt\5.12.3\android_armv7\lib\libQt5Widgets.prl:
C:\Qt\5.12.3\android_armv7\lib\libQt5Gui.prl:
C:\Qt\5.12.3\android_armv7\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qjalaliconverter.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile libqjalaliconverter.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents C:\Qt\5.12.3\android_armv7\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents mainwindow.h ..\JalaliDate\qdatejalali.h $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp mainwindow.cpp ..\JalaliDate\qdatejalali.cpp $(DISTDIR)\
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: C:\Qt\5.12.3\android_armv7\mkspecs\features\data\dummy.cpp
	E:\Android\SNDK\android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -D__ANDROID_API__=16 -target armv7-none-linux-androideabi -gcc-toolchain E:\Android\SNDK\android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING --sysroot=E:\Android\SNDK\android-ndk-r20/sysroot -isystem E:\Android\SNDK\android-ndk-r20/sysroot/usr/include/arm-linux-androideabi -isystem E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++/include -isystem E:\Android\SNDK\android-ndk-r20/sources/android/support/include -isystem E:\Android\SNDK\android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -Wall -W -dM -E -o moc_predefs.h C:\Qt\5.12.3\android_armv7\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qdatejalali.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qdatejalali.cpp
moc_mainwindow.cpp: mainwindow.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QMainWindow \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtguiglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlogging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qflags.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmutex.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtgui-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qwindowdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstring.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qchar.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringliteral.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringview.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiterator.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpair.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qregexp.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmargins.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpaintdevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrect.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsize.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpoint.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpalette.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qcolor.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qrgb.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qrgba64.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qbrush.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvector.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qmatrix.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpolygon.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qregion.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatastream.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiodevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qline.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtransform.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpainterpath.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qimage.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpixelformat.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpixmap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsharedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhash.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfont.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfontmetrics.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfontinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qcursor.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qkeysequence.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvariant.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdebug.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtextstream.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlocale.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qset.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qurl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qurlquery.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qfile.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qfiledevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qvector2d.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtouchdevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qicon.h \
		..\JalaliDate\qdatejalali.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QObject \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QDate \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatetime.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QStringList \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QTimer \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtimer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasictimer.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QMessageBox \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qmessagebox.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qdialog.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\QScreen \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qscreen.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QList \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QRect \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QSize \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QSizeF \
		C:\Qt\5.12.3\android_armv7\include\QtGui\QTransform \
		moc_predefs.h \
		C:\Qt\5.12.3\android_armv7\bin\moc.exe
	C:\Qt\5.12.3\android_armv7\bin\moc.exe $(DEFINES) --include D:/my_Projects/Programming/Qt/qjalaliconverter/moc_predefs.h -IC:/Qt/5.12.3/android_armv7/mkspecs/android-clang -ID:/my_Projects/Programming/Qt/qjalaliconverter -IC:/Qt/5.12.3/android_armv7/include -IC:/Qt/5.12.3/android_armv7/include/QtWidgets -IC:/Qt/5.12.3/android_armv7/include/QtGui -IC:/Qt/5.12.3/android_armv7/include/QtCore -IE:/Android/SNDK/android-ndk-r20/sysroot/usr/include/arm-linux-androideabi -IE:/Android/SNDK/android-ndk-r20/sources/cxx-stl/llvm-libc++/include -IE:/Android/SNDK/android-ndk-r20/sources/android/support/include -IE:/Android/SNDK/android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -IE:/Android/SNDK/android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/8.0.7/include -IE:/Android/SNDK/android-ndk-r20/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_qdatejalali.cpp: ..\JalaliDate\qdatejalali.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QObject \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlogging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qflags.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmutex.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstring.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qchar.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringliteral.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringview.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiterator.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpair.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qregexp.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QDate \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatetime.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhash.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QStringList \
		moc_predefs.h \
		C:\Qt\5.12.3\android_armv7\bin\moc.exe
	C:\Qt\5.12.3\android_armv7\bin\moc.exe $(DEFINES) --include D:/my_Projects/Programming/Qt/qjalaliconverter/moc_predefs.h -IC:/Qt/5.12.3/android_armv7/mkspecs/android-clang -ID:/my_Projects/Programming/Qt/qjalaliconverter -IC:/Qt/5.12.3/android_armv7/include -IC:/Qt/5.12.3/android_armv7/include/QtWidgets -IC:/Qt/5.12.3/android_armv7/include/QtGui -IC:/Qt/5.12.3/android_armv7/include/QtCore -IE:/Android/SNDK/android-ndk-r20/sysroot/usr/include/arm-linux-androideabi -IE:/Android/SNDK/android-ndk-r20/sources/cxx-stl/llvm-libc++/include -IE:/Android/SNDK/android-ndk-r20/sources/android/support/include -IE:/Android/SNDK/android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -IE:/Android/SNDK/android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/8.0.7/include -IE:/Android/SNDK/android-ndk-r20/sysroot/usr/include ..\JalaliDate\qdatejalali.h -o moc_qdatejalali.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		C:\Qt\5.12.3\android_armv7\bin\uic.exe
	C:\Qt\5.12.3\android_armv7\bin\uic.exe mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.obj: main.cpp mainwindow.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QMainWindow \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtguiglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlogging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qflags.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmutex.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtgui-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qwindowdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstring.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qchar.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringliteral.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringview.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiterator.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpair.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qregexp.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmargins.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpaintdevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrect.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsize.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpoint.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpalette.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qcolor.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qrgb.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qrgba64.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qbrush.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvector.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qmatrix.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpolygon.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qregion.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatastream.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiodevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qline.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtransform.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpainterpath.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qimage.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpixelformat.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpixmap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsharedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhash.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfont.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfontmetrics.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfontinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qcursor.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qkeysequence.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvariant.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdebug.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtextstream.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlocale.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qset.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qurl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qurlquery.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qfile.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qfiledevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qvector2d.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtouchdevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qicon.h \
		..\JalaliDate\qdatejalali.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QObject \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QDate \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatetime.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QStringList \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QTimer \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtimer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasictimer.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QMessageBox \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qmessagebox.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qdialog.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\QScreen \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qscreen.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QList \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QRect \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QSize \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QSizeF \
		C:\Qt\5.12.3\android_armv7\include\QtGui\QTransform \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QApplication \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qapplication.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcoreapplication.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qeventloop.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qdesktopwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qguiapplication.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

mainwindow.obj: mainwindow.cpp mainwindow.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QMainWindow \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qmainwindow.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtguiglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlogging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qflags.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmutex.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtgui-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qwindowdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstring.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qchar.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringliteral.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringview.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiterator.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpair.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qregexp.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmargins.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpaintdevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrect.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsize.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpoint.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpalette.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qcolor.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qrgb.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qrgba64.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qbrush.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvector.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qmatrix.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpolygon.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qregion.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatastream.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiodevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qline.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtransform.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpainterpath.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qimage.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpixelformat.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qpixmap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsharedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhash.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfont.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfontmetrics.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qfontinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qcursor.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qkeysequence.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvariant.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdebug.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtextstream.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlocale.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qset.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qurl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qurlquery.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qfile.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qfiledevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qvector2d.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qtouchdevice.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qtabwidget.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qicon.h \
		..\JalaliDate\qdatejalali.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QObject \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QDate \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatetime.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QStringList \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QTimer \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtimer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasictimer.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\QMessageBox \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qmessagebox.h \
		C:\Qt\5.12.3\android_armv7\include\QtWidgets\qdialog.h \
		C:\Qt\5.12.3\android_armv7\include\QtGui\QScreen \
		C:\Qt\5.12.3\android_armv7\include\QtGui\qscreen.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QList \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QRect \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QSize \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QSizeF \
		C:\Qt\5.12.3\android_armv7\include\QtGui\QTransform \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.obj mainwindow.cpp

qdatejalali.obj: ..\JalaliDate\qdatejalali.cpp ..\JalaliDate\qdatejalali.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QObject \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnamespace.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobal.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qconfig.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtcore-config.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsystemdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qprocessordetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qtypeinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qsysinfo.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlogging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qflags.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbasicatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qgenericatomic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qglobalstatic.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmutex.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qnumeric.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qversiontagging.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstring.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qchar.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qrefcount.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qarraydata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringliteral.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringview.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringbuilder.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qalgorithms.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qiterator.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhashfunctions.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qpair.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qbytearraylist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringlist.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qregexp.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qstringmatcher.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcoreevent.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qscopedpointer.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qmetatype.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qobject_impl.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QDate \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qdatetime.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qshareddata.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\qhash.h \
		C:\Qt\5.12.3\android_armv7\include\QtCore\QStringList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdatejalali.obj ..\JalaliDate\qdatejalali.cpp

moc_mainwindow.obj: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.obj moc_mainwindow.cpp

moc_qdatejalali.obj: moc_qdatejalali.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdatejalali.obj moc_qdatejalali.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a exit 1
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

